export const products = [
  {
    id: 1,
    name: "Nike Kobe 4 Protro Girl Dad",
    price: 200.0,
    image: "shoes/nike-kobe-4-protro-girl-dad-1.jpg",
    images: [
      "shoes/nike-kobe-4-protro-girl-dad-2.jpg",
      "shoes/nike-kobe-4-protro-girl-dad-3.jpg",
      "shoes/nike-kobe-4-protro-girl-dad-4.jpg",
      "shoes/nike-kobe-4-protro-girl-dad-5.jpg",
    ],
    link: "products-details.html",
    rating: 4.5,
    featured: true,
    dateAdded: "9/12/2024",
    description: "Pre-Owned",
    tags: ["kobe", "nike"],
  },
  {
    id: 2,
    name: "Nike Zoom Kobe 6 Blackout",
    price: 220.0,
    image: "shoes/nike-zoom-kobe-6-blackout-1.jpg",
    images: [
      "shoes/nike-zoom-kobe-6-blackout-2.jpg",
      "shoes/nike-zoom-kobe-6-blackout-3.jpg",
      "shoes/nike-zoom-kobe-6-blackout-4.jpg",
      "shoes/nike-zoom-kobe-6-blackout-5.jpg",
    ],
    link: "products-details.html",
    rating: 4.5,
    featured: true,
    dateAdded: "9/12/2024",
    description: "Pre-Owned",
    tags: ["kobe", "nike"],
  },
  {
    id: 3,
    name: "Nike Kobe 5 Protro 5 Rings",
    price: 190.0,
    image: "shoes/nike-kobe-5-protro-5-rings-1.jpg",
    images: [
      "shoes/nike-kobe-5-protro-5-rings-2.jpg",
      "shoes/nike-kobe-5-protro-5-rings-3.jpg",
      "shoes/nike-kobe-5-protro-5-rings-4.jpg",
      "shoes/nike-kobe-5-protro-5-rings-5.jpg",
    ],
    link: "products-details.html",
    rating: 4.5,
    featured: true,
    dateAdded: "9/12/2024",
    description: "Pre-Owned",
    tags: ["kobe", "nike"],
  },
  {
    id: 4,
    name: "Nike Kobe 6 Protro Reverse Grinch",
    price: 200.0,
    image: "shoes/nike-kobe-6-protro-reverse-grinch-1.jpg",
    images: [
      "shoes/nike-kobe-6-protro-reverse-grinch-2.jpg",
      "shoes/nike-kobe-6-protro-reverse-grinch-3.jpg",
      "shoes/nike-kobe-6-protro-reverse-grinch-4.jpg",
      "shoes/nike-kobe-6-protro-reverse-grinch-5.jpg",
    ],
    link: "products-details.html",
    rating: 5.0,
    featured: true,
    dateAdded: "9/12/2024",
    description: "Pre-Owned",
    tags: ["kobe", "nike"],
  },
];
