// products.js
export const products = [
  {
    id: 1,
    name: "Downshifter Sports Shoes",
    price: 50.0,
    image: "images/product-11.jpg",
    images: [
      "images/product-11.jpg",
      "images/product-5.jpg",
      "images/product-11.jpg",
      "images/product-5.jpg",
    ],
    link: "products-details.html",
    rating: 4.5,
    featured: true,
    dateAdded: "12/11/2024",
    description: "id 1",
  },
  {
    id: 2,
    name: "Lace-Up Running Shoes",
    price: 35.0,
    image: "images/product-2.jpg",
    images: [
      "images/product-2.jpg",
      "images/product-5.jpg",
      "images/product-11.jpg",
      "images/product-5.jpg",
    ],
    link: "products-details.html",
    rating: 4.5,
    featured: true,
    dateAdded: "12/11/2024",
    description: "id 2",
  },
  {
    id: 3,
    name: "Lace Fastening Shoes",
    price: 15.0,
    image: "images/product-3.jpg",
    images: [
      "images/product-3.jpg",
      "images/product-5.jpg",
      "images/product-11.jpg",
      "images/product-5.jpg",
    ],
    link: "products-details.html",
    rating: 4.0,
    featured: true,
    dateAdded: "12/11/2024",
    description: "id 3",
  },
  {
    id: 4,
    name: "Flat Lace-Fastening Shoes",
    price: 48.0,
    image: "images/product-10.jpg",
    images: [
      "images/product-10.jpg",
      "images/product-5.jpg",
      "images/product-11.jpg",
      "images/product-5.jpg",
    ],
    link: "products-details.html",
    rating: 3.5,
    featured: true,
    dateAdded: "12/11/2024",
    description: "id 4",
  },
  {
    id: 5,
    name: "Flat Heel Gray Shoes",
    price: 50.0,
    image: "images/product-5.jpg",
    images: [
      "images/product-5.jpg",
      "images/product-5.jpg",
      "images/product-11.jpg",
      "images/product-5.jpg",
    ],
    link: "products-details.html",
    rating: 4.5,
    featured: false,
    dateAdded: "12/11/2024",
    description: "id 5",
  },
  {
    id: 6,
    name: "HRX Men's Cotton Socks",
    price: 9.0,
    image: "images/product-7.jpg",
    images: [
      "images/product-7.jpg",
      "images/product-5.jpg",
      "images/product-11.jpg",
      "images/product-5.jpg",
    ],
    link: "products-details.html",
    rating: 4.0,
    featured: false,
    dateAdded: "12/11/2024",
    description: "id 6",
  },
  {
    id: 7,
    name: "HRX Men's Cotton Socks",
    price: 9.0,
    image: "images/product-7.jpg",
    images: [
      "images/product-7.jpg",
      "images/product-5.jpg",
      "images/product-11.jpg",
      "images/product-5.jpg",
    ],
    link: "products-details.html",
    rating: 4.0,
    featured: false,
    dateAdded: "12/11/2024",
    description: "id 7",
  },
  {
    id: 8,
    name: "HRX Men's Cotton Socks",
    price: 9.0,
    image: "images/product-7.jpg",
    images: [
      "images/product-7.jpg",
      "images/product-5.jpg",
      "images/product-11.jpg",
      "images/product-5.jpg",
    ],
    link: "products-details.html",
    rating: 4.0,
    featured: false,
    dateAdded: "12/11/2024",
    description: "id 8",
  },
  {
    id: 9,
    name: "Downshifter Sports Shoes",
    price: 60.0,
    image: "images/product-11.jpg",
    images: [
      "images/product-11.jpg",
      "images/product-5.jpg",
      "images/product-11.jpg",
      "images/product-5.jpg",
    ],
    link: "products-details.html",
    rating: 4.5,
    featured: false,
    dateAdded: "12/11/2024",
    description: "id 9",
  },
  {
    id: 10,
    name: "Lace-Up Running Shoes",
    price: 35.0,
    image: "images/product-2.jpg",
    images: [
      "images/product-2.jpg",
      "images/product-5.jpg",
      "images/product-11.jpg",
      "images/product-5.jpg",
    ],
    link: "products-details.html",
    rating: 5.0,
    featured: false,
    dateAdded: "12/11/2024",
    description: "id 10",
  },
  {
    id: 11,
    name: "Lace Fastening Shoes",
    price: 15.0,
    image: "images/product-3.jpg",
    images: [
      "images/product-3.jpg",
      "images/product-5.jpg",
      "images/product-11.jpg",
      "images/product-5.jpg",
    ],
    link: "products-details.html",
    rating: 4.0,
    featured: false,
    dateAdded: "12/11/2024",
    description: "id 11",
  },
  {
    id: 12,
    name: "Flat Lace-Fastening Shoes",
    price: 48.0,
    image: "images/product-10.jpg",
    images: [
      "images/product-10.jpg",
      "images/product-5.jpg",
      "images/product-11.jpg",
      "images/product-5.jpg",
    ],
    link: "products-details.html",
    rating: 3.5,
    featured: false,
    dateAdded: "12/11/2024",
    description: "id 12",
  },
  {
    id: 13,
    name: "Flat Heel Gray Shoes",
    price: 50.0,
    image: "images/product-5.jpg",
    images: [
      "images/product-5.jpg",
      "images/product-5.jpg",
      "images/product-11.jpg",
      "images/product-5.jpg",
    ],
    link: "products-details.html",
    rating: 4.2,
    featured: false,
    dateAdded: "12/11/2024",
    description: "id 13",
  },
  {
    id: 14,
    name: "HRX Men's Cotton Socks",
    price: 9.0,
    image: "images/product-7.jpg",
    images: [
      "images/product-7.jpg",
      "images/product-5.jpg",
      "images/product-11.jpg",
      "images/product-5.jpg",
    ],
    link: "products-details.html",
    rating: 4.0,
    featured: false,
    dateAdded: "12/11/2024",
    description: "id 14",
  },
  {
    id: 15,
    name: "HRX Men's Cotton Socks",
    price: 9.0,
    image: "images/product-7.jpg",
    images: [
      "images/product-7.jpg",
      "images/product-5.jpg",
      "images/product-11.jpg",
      "images/product-5.jpg",
    ],
    link: "products-details.html",
    rating: 4.0,
    featured: false,
    dateAdded: "12/11/2024",
    description: "id 15",
  },
  {
    id: 16,
    name: "HRX Men's Cotton Socks",
    price: 9.0,
    image: "images/product-7.jpg",
    images: [
      "images/product-7.jpg",
      "images/product-5.jpg",
      "images/product-11.jpg",
      "images/product-5.jpg",
    ],
    link: "products-details.html",
    rating: 4.0,
    featured: false,
    dateAdded: "12/11/2024",
    description: "id 16",
  },
  {
    id: 17,
    name: "Downshifter Sports Shoes",
    price: 60.0,
    image: "images/product-11.jpg",
    images: [
      "images/product-11.jpg",
      "images/product-5.jpg",
      "images/product-11.jpg",
      "images/product-5.jpg",
    ],
    link: "products-details.html",
    rating: 4.5,
    featured: false,
    dateAdded: "12/11/2024",
    description: "id 17",
  },
  {
    id: 18,
    name: "Lace-Up Running Shoes",
    price: 35.0,
    image: "images/product-2.jpg",
    images: [
      "images/product-2.jpg",
      "images/product-5.jpg",
      "images/product-11.jpg",
      "images/product-5.jpg",
    ],
    link: "products-details.html",
    rating: 4.5,
    featured: false,
    dateAdded: "12/11/2024",
    description: "id 18",
  },
  {
    id: 19,
    name: "Lace Fastening Shoes",
    price: 15.0,
    image: "images/product-3.jpg",
    images: [
      "images/product-3.jpg",
      "images/product-5.jpg",
      "images/product-11.jpg",
      "images/product-5.jpg",
    ],
    link: "products-details.html",
    rating: 4.0,
    featured: false,
    dateAdded: "12/11/2024",
    description: "id 19",
  },
  {
    id: 20,
    name: "Flat Lace-Fastening Shoes",
    price: 48.0,
    image: "images/product-10.jpg",
    images: [
      "images/product-10.jpg",
      "images/product-5.jpg",
      "images/product-11.jpg",
      "images/product-5.jpg",
    ],
    link: "products-details.html",
    rating: 3.5,
    featured: false,
    dateAdded: "12/11/2024",
    description: "id 20",
  },
  {
    id: 21,
    name: "Flat Heel Gray Shoes",
    price: 50.0,
    image: "images/product-5.jpg",
    images: [
      "images/product-5.jpg",
      "images/product-5.jpg",
      "images/product-11.jpg",
      "images/product-5.jpg",
    ],
    link: "products-details.html",
    rating: 4.5,
    featured: false,
    dateAdded: "12/11/2024",
    description: "id 21",
  },
  {
    id: 22,
    name: "HRX Men's Cotton Socks",
    price: 9.0,
    image: "images/product-7.jpg",
    images: [
      "images/product-7.jpg",
      "images/product-5.jpg",
      "images/product-11.jpg",
      "images/product-5.jpg",
    ],
    link: "products-details.html",
    rating: 4.0,
    featured: false,
    dateAdded: "12/11/2024",
    description: "id 22",
  },
  {
    id: 23,
    name: "HRX Men's Cotton Socks",
    price: 9.0,
    image: "images/product-7.jpg",
    images: [
      "images/product-7.jpg",
      "images/product-5.jpg",
      "images/product-11.jpg",
      "images/product-5.jpg",
    ],
    link: "products-details.html",
    rating: 4.0,
    featured: false,
    dateAdded: "12/11/2024",
    description: "id 23",
  },
  {
    id: 24,
    name: "HRX Men's Cotton Socks",
    price: 9.0,
    image: "images/product-7.jpg",
    images: [
      "images/product-7.jpg",
      "images/product-5.jpg",
      "images/product-11.jpg",
      "images/product-5.jpg",
    ],
    link: "products-details.html",
    rating: 4.0,
    featured: false,
    dateAdded: "12/11/2024",
    description: "id 24",
  },
];
